services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./database:/database
    entrypoint: [ "/database/restore.sh" ]

  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: fastapi_backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongo_data:
